#pragma once

#include <memory>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMInstaller
{
	namespace Properties
	{


		/// <summary>
		///   A strongly-typed resource class, for looking up localized strings, etc.
		/// </summary>
		// This class was auto-generated by the StronglyTypedResourceBuilder
		// class via a tool like ResGen or Visual Studio.
		// To add or remove a member, edit your .ResX file then rerun ResGen
		// with the /str option, or rebuild your VS project.
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")][System.Diagnostics.DebuggerNonUserCodeAttribute()][System.Runtime.CompilerServices.CompilerGeneratedAttribute()] public class Resources
		class Resources : public std::enable_shared_from_this<Resources>
		{

		private:
			static std::shared_ptr<System::Resources::ResourceManager> resourceMan;

			static std::shared_ptr<System::Globalization::CultureInfo> resourceCulture;

		public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] internal Resources()
			Resources()
			{
			}

			/// <summary>
			///   Returns the cached ResourceManager instance used by this class.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] public static System.Resources.ResourceManager ResourceManager
			const static std::shared_ptr<System::Resources::ResourceManager> &getResourceManager() const
			{
				if (Object::ReferenceEquals(resourceMan, nullptr))
				{
					std::shared_ptr<System::Resources::ResourceManager> temp = std::make_shared<System::Resources::ResourceManager>(L"EDMInstaller.Properties.Resources", Resources::typeid->Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}

			/// <summary>
			///   Overrides the current thread's CurrentUICulture property for all
			///   resource lookups using this strongly typed resource class.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] public static System.Globalization.CultureInfo Culture
			const static std::shared_ptr<System::Globalization::CultureInfo> &getCulture() const
			{
				return resourceCulture;
			}
			static void setCulture(const std::shared_ptr<System::Globalization::CultureInfo> &value)
			{
				resourceCulture = value;
			}
		};
	}
}
